"""Counterfactual relevance-aligned magnitude intervention (SIGIR-Final-Tasks Item 1).

Builds on scripts/magnitude_perturbation.py (rank-preserving sensitivity) by adding
the CAUSAL arm the reviewer's #1 / #38 requires:

  World+ : within each rank bucket, amplify the relevant document's score margin
           above the bucket's non-relevant mean (rho in {1.25,1.5,2.0}); rank preserved.
  World- : within each rank bucket, push the relevant document BELOW the non-relevant
           mean (reverse the margin); rank preserved.

Because ranks are held fixed by construction, RRF (rank-only) output is identical
across all worlds => any CombSUM/CombMNZ change is attributable to magnitude, and the
direction (World+ > orig > World-) causally implicates relevance-aligned magnitude.

Also reproduces/extends the descriptive H3a arm:
  * rank-conditioned relevance probability P(y=1 | delta_k large) vs small
  * E[s|y=1,r] - E[s|y=0,r] per rank bucket

Inputs: docs/papers/Journal A/appendix_alpha/<ds>_comp_{1.0,0.0}_n100.json
        (generated by scripts/gen_component_traces_n100.py)
        <run>/query_gold.json

Outputs: docs/papers/Journal A/appendix_stats/counterfactual_magnitude.{json,md}
         (SIGIR-Final-Results.md is filled in separately by the user after review)
"""
import json
import sys
from pathlib import Path

import numpy as np

PROJ = Path(r"E:/PHD/GraphRag-Implementations/YaALI/knowledge-graph-builder")
sys.path.insert(0, str(PROJ))
from semantic_folding import fusion_operators as fo

ALPHA_DIR = PROJ / "docs/papers/Journal A/appendix_alpha"
OUT_DIR = PROJ / "docs/papers/Journal A/appendix_stats"
OUT_DIR.mkdir(parents=True, exist_ok=True)

DATASETS = {
    "n100": {
        "hotpotqa": PROJ / "outputs/hotpotqa_benchmark/runs/run_20260824_032535/query_gold.json",
        "musique":  PROJ / "outputs/musique_benchmark/runs/run_20260824_033236/query_gold.json",
        "nq_rear":  PROJ / "outputs/nq_rear_benchmark/runs/run_20260824_033353/query_gold.json",
    },
    "n10": {
        "hotpotqa": PROJ / "outputs/hotpotqa_benchmark/runs/run_20260822_163656/query_gold.json",
        "musique":  PROJ / "outputs/musique_benchmark/runs/run_20260822_191925/query_gold.json",
        "scifact":  PROJ / "outputs/scifact_benchmark/runs/run_20260822_191507/query_gold.json",
        "2wikimultihopqa": PROJ / "outputs/2wikimultihopqa_benchmark/runs/run_20260822_100044/query_gold.json",
    },
}


def comp_path(ds, n):
    """Component trace filename for dataset ds at sample size n."""
    if n == 100:
        return ALPHA_DIR / f"{ds}_comp_1.0_n100.json", ALPHA_DIR / f"{ds}_comp_0.0_n100.json"
    return ALPHA_DIR / f"{ds}_comp_1.0.json", ALPHA_DIR / f"{ds}_comp_0.0.json"


OPERATORS = ["rrf", "combsum", "combmnz", "linear", "borda", "zscore", "minmax"]
RHO_LIST = [1.25, 1.5, 2.0]
ALPHA_NEG = 0.5  # World-: gold placed at midpoint between its score and non-gold mean
SEED = 42


def load_components(path):
    raw = json.loads(Path(path).read_text(encoding="utf-8"))
    return [dict(q["results"]) for q in raw]


def ranks_from_scores(scores):
    """Return {doc: rank} (1-based) from a score dict. Stable tie-break by doc_id."""
    order = sorted(scores.items(), key=lambda kv: (-kv[1], kv[0]))
    return {d: i + 1 for i, (d, _) in enumerate(order)}


def fuse(sf, sp, operator):
    """Fuse two per-doc score dicts with one operator; return ranked doc list."""
    docs = sorted(set(sf) | set(sp))
    sfv = {d: sf.get(d, 0.0) for d in docs}
    spv = {d: sp.get(d, 0.0) for d in docs}
    if operator == "borda":
        n_docs = len(docs)
        fused = fo.fuse(operator, sfv, spv, n_docs=n_docs)
    else:
        fused = fo.fuse(operator, sfv, spv, k=60)
    # fo.fuse returns {doc: score}; rank by score desc
    return [d for d, _ in sorted(fused.items(), key=lambda kv: -kv[1])]


def mrr_of(ranked, gold):
    for rank, d in enumerate(ranked, 1):
        if d in gold:
            return 1.0 / rank
    return 0.0


def kendall_tau(ranked_a, ranked_b):
    """Kendall's tau-b over two ranked lists (ties neither concordant nor discordant).

    Uses 1-based rank lists; ties (equal position) are counted as neither concordant
    nor discordant, so identical RRF tie-groups score tau = 1.0.
    """
    pos_a = {d: i for i, d in enumerate(ranked_a)}
    pos_b = {d: i for i, d in enumerate(ranked_b)}
    docs = list(set(pos_a) & set(pos_b))
    n = len(docs)
    if n < 2:
        return 1.0
    conc = disc = tie = 0
    for i in range(n):
        for j in range(i + 1, n):
            a = pos_a[docs[i]] - pos_a[docs[j]]
            b = pos_b[docs[i]] - pos_b[docs[j]]
            if a * b > 0:
                conc += 1
            elif a * b < 0:
                disc += 1
            else:
                tie += 1
    denom = (conc + disc + tie)  # tau-b denominator uses ties in either variable
    return conc / denom if denom else 1.0


def rrf_ranks_identical(sf_a, sp_a, sf_b, sp_b):
    """True iff RRF per-doc ranks are identical between (a) and (b) worlds.

    RRF is a pure function of per-signal ranks; comparing the resulting rank assignment
    (including tie groups, broken by doc_id) is the exact invariance test.
    """
    fa = fo.fuse("rrf", sf_a, sp_a, k=60)
    fb = fo.fuse("rrf", sf_b, sp_b, k=60)
    ra = ranks_from_scores(fa)
    rb = ranks_from_scores(fb)
    return all(rb.get(d) == ra.get(d) for d in ra) and set(ra) == set(rb)


def build_worlds(sf, sp, gold_set, rho, rng):
    """Return dict world_name -> (sf_world, sp_world) rank-preserving transforms.

    Transform is applied to BOTH signals (so the cross-signal geometry shifts
    consistently); within-signal rank is preserved by construction.
    """
    worlds = {}

    # A: original
    worlds["orig"] = (dict(sf), dict(sp))

    # B: rank-preserving compression (scale both by 0.5)
    worlds["compress"] = ({d: 0.5 * v for d, v in sf.items()},
                          {d: 0.5 * v for d, v in sp.items()})

    # C: rank-preserving random monotone remap of magnitudes (seeded)
    def rpr(scores):
        # sort by (-value, doc_id) — identical key order to ranks_from_scores' sort,
        # so the strictly-increasing new values reproduce the exact same ranking
        order = sorted(scores.items(), key=lambda kv: (-kv[1], kv[0]))
        n = len(order)
        newv = np.linspace(float(n), 1.0, n)  # strictly decreasing => highest original keeps highest rank
        return {d: float(nv) for (d, _), nv in zip(order, newv)}
    worlds["rpr"] = (rpr(sf), rpr(sp))

    # D: World+  (relevance-aligned amplification) — both signals, rank-preserving
    for rho in RHO_LIST:
        worlds[f"worldpos_{rho}"] = (
            _align(sf, gold_set, rho, +1),
            _align(sp, gold_set, rho, +1),
        )
    # E: World-  (anti-relevance) — both signals, rank-preserving
    worlds["worldneg"] = (
        _align(sf, gold_set, -1, None),
        _align(sp, gold_set, -1, None),
    )
    return worlds


def _align(scores, gold_set, rho, sign):
    """Rank-preserving relevance-aligned transform on a SINGLE signal.

    sign=+1 (World+): within each rank bucket, push gold's score further above the
        bucket's non-gold mean by factor rho. New value is placed strictly between the
        gold doc's two rank-neighbours so its rank cannot change.
    sign=-1 (World-): push gold's score to the midpoint between its current score and
        the bucket non-gold mean (margin reversed), still strictly inside its rank slot.
    Non-gold docs are unchanged.
    """
    order = sorted(scores.items(), key=lambda kv: (-kv[1], kv[0]))  # rank 1 = highest
    docs = [d for d, _ in order]
    vals = np.array([v for _, v in order], dtype=float)
    n = len(docs)
    rank = {d: i for i, d in enumerate(docs)}  # 0-based position
    out = dict(scores)
    bsize = max(5, n // 10)
    for start in range(0, n, bsize):
        end = min(n, start + bsize)
        bucket = list(range(start, end))
        golds_in = [i for i in bucket if docs[i] in gold_set]
        non_golds = [i for i in bucket if docs[i] not in gold_set]
        if not golds_in or not non_golds:
            continue
        m = float(np.mean(vals[non_golds]))
        for i in golds_in:
            cur = float(vals[i])
            if sign == +1:
                target = m + rho * (cur - m)
            else:
                target = 0.5 * (cur + m)
            # strictly inside rank slot: between rank-neighbour scores
            above = vals[i - 1] if i > 0 else cur + 1.0
            below = vals[i + 1] if i < n - 1 else cur - 1.0
            newv = min(target, above - 1e-9)
            newv = max(newv, below + 1e-9)
            out[docs[i]] = float(newv)
            vals[i] = newv
    return out


def rank_conditioned_gap(sf, sp, gold_set):
    """H3a extension: E[s|y=1,r] - E[s|y=0,r] per rank bucket; AUC of score;
    P(y=1 | delta_k large) vs small for k in {2,5,10}."""
    merged = {}
    for d in set(sf) | set(sp):
        merged[d] = (sf.get(d, 0.0) + sp.get(d, 0.0)) / 2.0
    order = sorted(merged.items(), key=lambda kv: -kv[1])
    docs = [d for d, _ in order]
    # gold bucket membership by rank position (1-based)
    buckets = {"1": [], "2-3": [], "4-5": [], "6-10": []}
    for i, d in enumerate(docs, 1):
        if i == 1:
            b = "1"
        elif i <= 3:
            b = "2-3"
        elif i <= 5:
            b = "4-5"
        elif i <= 10:
            b = "6-10"
        else:
            continue
        buckets[b].append((d, merged[d], d in gold_set))
    gap = {}
    for b, rows in buckets.items():
        if not rows:
            continue
        y1 = [s for _, s, g in rows if g]
        y0 = [s for _, s, g in rows if not g]
        if y1 and y0:
            gap[b] = float(np.mean(y1) - np.mean(y0))
        else:
            gap[b] = None
    # relevance probability by separation
    sorted_scores = sorted([s for _, s in merged.items()], reverse=True)
    def p_y_given_sep(k, large):
        # delta_k = top - kth; large vs small by median split of deltas
        deltas = []
        for d, s in merged.items():
            top = sorted_scores[0]
            dk = top - s  # separation from top (prox for k=1); use rank-based
            deltas.append((dk, d in gold_set))
        dvals = np.array([x[0] for x in deltas])
        med = np.median(dvals)
        sub = [g for dv, g in deltas if (dv >= med) == large]
        return float(np.mean(sub)) if sub else None
    prob = {
        f"delta_large": p_y_given_sep(None, True),
        f"delta_small": p_y_given_sep(None, False),
    }
    # AUC of merged score separating gold
    pos = [s for d, s in merged.items() if d in gold_set]
    neg = [s for d, s in merged.items() if d not in gold_set]
    auc = _auc(pos, neg)
    return {"rank_gap": gap, "prob_relevant_by_separation": prob, "auc": auc}


def _auc(pos, neg):
    if not pos or not neg:
        return None
    diffs = [p - n for p in pos for n in neg]
    return sum(1 for d in diffs if d > 0) / len(diffs)


def main():
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=100, choices=[10, 100])
    args = ap.parse_args()
    N = args.n
    rng = np.random.default_rng(SEED)
    results = {"sample_size": N, "datasets": {}, "summary": {}}
    ds_map = DATASETS[f"n{N}"]
    for ds, gold_path in ds_map.items():
        print(f"=== {ds} (n={N}) ===")
        c1, c0 = comp_path(ds, N)
        if not (c1.exists() and c0.exists()):
            print(f"  SKIP {ds}: missing component traces {c1.name}/{c0.name}")
            continue
        sf = load_components(c1)
        sp = load_components(c0)
        gold = json.loads(gold_path.read_text(encoding="utf-8"))
        nq = min(len(sf), len(sp))
        per_op_world = {op: {} for op in OPERATORS}
        invariance = {}
        rank_gaps = []
        for qi in range(nq):
            g = set(gold.get(str(qi), []))
            if not g:
                continue
            worlds = build_worlds(sf[qi], sp[qi], g, 1.5, rng)
            # store per-world ranks per operator
            for wname, (wsf, wsp) in worlds.items():
                ranked = {op: fuse(wsf, wsp, op) for op in OPERATORS}
                for op in OPERATORS:
                    per_op_world[op].setdefault(wname, []).append(mrr_of(ranked[op], g))
            # invariance: RRF identical across worlds (exact per-doc rank equality)
            base_sf, base_sp = sf[qi], sp[qi]
            inv = True
            for wname, (wsf, wsp) in worlds.items():
                if not rrf_ranks_identical(base_sf, base_sp, wsf, wsp):
                    inv = False
                    break
            invariance[qi] = 1.0 if inv else 0.0
            rank_gaps.append(rank_conditioned_gap(sf[qi], sp[qi], g))

        # aggregate MRR per operator per world
        mrr_table = {}
        for op in OPERATORS:
            mrr_table[op] = {}
            for wname in per_op_world[op]:
                vals = per_op_world[op][wname]
                if vals:
                    mrr_table[op][wname] = float(np.mean(vals))

        # bootstrap CI on CombSUM worldpos_1.5 - orig and orig - worldneg
        def boot_diff(op, w_hi, w_lo, B=10000):
            a = np.array(per_op_world[op][w_hi])
            b = np.array(per_op_world[op][w_lo])
            diffs = a - b
            if len(diffs) < 2:
                return None
            idx = rng.integers(0, len(diffs), size=(B, len(diffs)))
            boots = diffs[idx].mean(axis=1)
            return (float(np.mean(diffs)),
                    float(np.percentile(boots, 2.5)),
                    float(np.percentile(boots, 97.5)))

        ci_pos = boot_diff("combsum", "worldpos_1.5", "orig")
        ci_neg = boot_diff("combsum", "orig", "worldneg")
        ci_pos_rrf = boot_diff("rrf", "worldpos_1.5", "orig")
        ci_neg_rrf = boot_diff("rrf", "orig", "worldneg")

        # average rank gap (H3a)
        avg_gap = {}
        for b in ["1", "2-3", "4-5", "6-10"]:
            vals = [rg["rank_gap"].get(b) for rg in rank_gaps if rg["rank_gap"].get(b) is not None]
            avg_gap[b] = float(np.mean(vals)) if vals else None
        avg_prob = {
            "delta_large": _mean([rg["prob_relevant_by_separation"]["delta_large"] for rg in rank_gaps]),
            "delta_small": _mean([rg["prob_relevant_by_separation"]["delta_small"] for rg in rank_gaps]),
            "auc": _mean([rg["auc"] for rg in rank_gaps]),
        }

        min_inv = float(np.min(list(invariance.values()))) if invariance else None
        results["datasets"][ds] = {
            "n_queries": len(invariance),
            "mrr_table": mrr_table,
            "combsum_worldpos_orig_CI": ci_pos,
            "combsum_orig_worldneg_CI": ci_neg,
            "rrf_worldpos_orig_CI": ci_pos_rrf,
            "rrf_orig_worldneg_CI": ci_neg_rrf,
            "rrf_invariance_min_tau": min_inv,
            "rank_gap_H3a": avg_gap,
            "relevance_prob_H3a": avg_prob,
        }
        print(f"  n={len(invariance)} RRF invariance tau_min={min_inv:.4f}")
        print(f"  CombSUM MRR: orig={mrr_table['combsum']['orig']:.4f} "
              f"world+={mrr_table['combsum']['worldpos_1.5']:.4f} "
              f"world-={mrr_table['combsum']['worldneg']:.4f}")
        print(f"  CombSUM +vs orig CI={ci_pos}; orig vs - CI={ci_neg}")
        print(f"  RRF invariance (should be ~0 delta): +vs orig CI={ci_pos_rrf}")

    out = OUT_DIR / f"counterfactual_magnitude_n{N}.json"
    out.write_text(json.dumps(results, indent=2), encoding="utf-8")

    # markdown
    lines = [f"# Counterfactual Relevance-Aligned Magnitude Intervention (Item 1, n={N})\n",
             "Rank-preserving; RRF invariant by construction. CombSUM/CombMNZ changes "
             "are attributable to magnitude, not rank.\n"]
    for ds, d in results["datasets"].items():
        lines += [f"\n## {ds} (n={d['n_queries']})\n",
                  f"RRF invariance minimum Kendall τ across worlds: **{d['rrf_invariance_min_tau']:.4f}** "
                  f"(1.0 = ranks identical => RRF identical, as required).\\n",
                  "\n### MRR by operator × world\n",
                  "| Operator | orig | compress | rpr | " +
                  " | ".join(f"world+ (ρ={rho})" for rho in RHO_LIST) +
                  " | world− |",
                  "|----------|-----:|--------:|----:|" +
                  ":|" * len(RHO_LIST) + "------:|"]
        mt = d["mrr_table"]
        for op in OPERATORS:
            cells = [f"{mt[op].get('orig',0):.4f}", f"{mt[op].get('compress',0):.4f}",
                     f"{mt[op].get('rpr',0):.4f}"]
            cells += [f"{mt[op].get(f'worldpos_{rho}',0):.4f}" for rho in RHO_LIST]
            cells.append(f"{mt[op].get('worldneg',0):.4f}")
            lines.append(f"| {op} | " + " | ".join(cells) + " |")
        lines += ["\n### Causal contrast (CombSUM, bootstrap 95% CI, B=10000)\n",
                  f"- World+ vs orig: ΔMRR = {d['combsum_worldpos_orig_CI'][0]:+.4f} "
                  f"(95% CI [{d['combsum_worldpos_orig_CI'][1]:+.4f}, {d['combsum_worldpos_orig_CI'][2]:+.4f}])\\n",
                  f"- orig vs World−: ΔMRR = {d['combsum_orig_worldneg_CI'][0]:+.4f} "
                  f"(95% CI [{d['combsum_orig_worldneg_CI'][1]:+.4f}, {d['combsum_orig_worldneg_CI'][2]:+.4f}])\\n",
                  f"- RRF World+ vs orig ΔMRR = {d['rrf_worldpos_orig_CI'][0]:+.4f} "
                  f"(must be ~0; invariance check)\\n",
                  "\n### H3a — rank-conditioned relevance gap E[s|y=1,r]−E[s|y=0,r]\\n",
                  "| rank bucket | gap |", "|------------|----:|"]
        for b in ["1", "2-3", "4-5", "6-10"]:
            g = d["rank_gap_H3a"].get(b)
            lines.append(f"| {b} | {g:.4f} |" if g is not None else f"| {b} | n/a |")
        rp = d["relevance_prob_H3a"]
        lines.append(f"\nP(y=1 | large separation) = {rp['delta_large']:.3f}; "
                     f"P(y=1 | small separation) = {rp['delta_small']:.3f}; "
                     f"AUC(score) = {rp['auc']:.3f}\\n")
    (OUT_DIR / f"counterfactual_magnitude_n{N}.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"\nwrote {out} and counterfactual_magnitude_n{N}.md")


def _mean(xs):
    xs = [x for x in xs if x is not None]
    return float(np.mean(xs)) if xs else None


if __name__ == "__main__":
    main()
